version: 2
updates:
  # Terraform dependencies
  - package-ecosystem: "terraform"
    directory: "/Terraform"  # Path to the Terraform configurations
    schedule:
      interval: "weekly"  # Check for updates weekly
      day: "tuesday"  # Check on Tuesday
      time: "18:00"  # Time in UTC
    security-updates-only: true  # Only update dependencies with security fixes

  # Helm chart dependencies
  - package-ecosystem: "helm"
    directory: "/Airbyte"  # Path to the Helm charts (under the Airbyte directory)
    schedule:
      interval: "weekly"  # Check for updates weekly
      day: "tuesday"  # Check on Tuesday
      time: "18:00"  # Time in UTC
    security-updates-only: true  # Only update dependencies with security fixes
