apiVersion: v1
kind: Secret
metadata:
  name: airbyte-config-secrets
type: Opaque
stringData:
  license-key: <PLACE_HOLDER_KEY>
  # Admin Info
  instance-admin-email: nikhil.maddikunta@gov.bc.ca
  instance-admin-password: <PLACE_ADMIN_PASS>

  # General Info
  airbyte-url: {{ .Values.global.airbyteUrl | quote }}
  airbyte-edition: {{ .Values.global.edition | quote }}

  # Database Credentials 
  database-host: {{ .Values.global.database.host | quote }}
  database-port: {{ .Values.global.database.port | quote }}
  database-name: {{ .Values.global.database.database | quote }}
  database-user: {{ .Values.global.database.user | quote }}
  database-password: "airbyteuserpdems"  # Replace this hardcoded password if loading dynamically

  # S3 Storage
  s3-region: {{ .Values.global.storage.s3.region | quote }}
  s3-log-bucket: {{ .Values.global.storage.bucket.log | quote }}
  s3-state-bucket: {{ .Values.global.storage.bucket.state | quote }}
  s3-workload-output-bucket: {{ .Values.global.storage.bucket.workloadOutput | quote }}
  s3-authentication-type: {{ .Values.global.storage.s3.authenticationType | quote }}
