postgresql:
  enabled: false
global:
  edition: enterprise
  airbyteUrl: https://airbyte.company.example
  auth:
    instanceAdmin:
      firstName: Alex
      lastName:  Aleshchenko
    
  database:
    # -- Secret name where database credentials are stored
    secretName: "airbyte-config-secrets"

    # -- The database host
    hostSecretKey: "database-host" 

    # -- The database port
    portSecretKey: "database-port" 

    # -- The database name
    databaseSecretKey: "database-name" 

    # -- The database user
    userSecretKey: "database-user" 

    passwordSecretKey: "database-password" 

  storage:
    type: S3
    bucket: ## S3 bucket names that you've created. We recommend storing the following all in one bucket.
      log: airbyte-pdems
      state: airbyte-pdems
      workloadOutput: airbyte-pdems
    s3:
      region: ca-central-1 
      authenticationType: instanceProfile  
  

