postgresql:
  enabled: true
global:
  edition: enterprise
  airbyteUrl: http://127.0.0.1:8080
  auth:
    instanceAdmin:
      firstName: Nikhil
      lastName:  Maddikunta
  storage:
    type: "S3"
    bucket: ## S3 bucket names that you've created. We recommend storing the following all in one bucket.
      log: airbyte-pdems
      state: airbyte-pdems
      workloadOutput: airbyte-pdems
    s3:
      region: ca-central-1 
      authenticationType: instanceProfile