name: EKS Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'select the environment to deploy'
        required: true
        type: choice
        options:
        - dev
        - sandbox
        - prod 

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    steps:

      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: setup node.js for terraform 
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd jag-k8s-aws-iac-sandbox
          terraform init -backend-config="bucket=${{ secrets.TERRAFORM_BACKEND_BUCKET }}" -backend-config="dynamodb_table=${{ secrets.TERRAFORM_STATE_LOCK_TABLE }}" -backend-config="region=${{ secrets.AWS_REGION }}"
  
      - name: Terraform Plan
        run: |
          cd jag-k8s-aws-iac-sandbox
          terraform plan -out=tfplan

      - name: Terraform Apply
        run: |
          cd jag-k8s-aws-iac-sandbox
          terraform apply -auto-approve tfplan

